version: '3'
services:
    tdd-web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ../:/var/www
        ports:
            - 8889:80
        links:
            - tdd-app
    tdd-app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ../:/var/www
        links:
            - tdd-database
    tdd-database:
        image: mariadb
        command: --sql_mode=""
        environment:
            - "MYSQL_ROOT_PASSWORD=pass"
            - "MYSQL_DATABASE=tdd"
            - "innodb_file_format=Barracuda"
            - "innodb_file_per_table=ON"

        ports:
            - 33065:3306
        volumes:
            - ./data:/var/lib/mysql
    tdd-redis:
        image: "redis:alpine"
        container_name: redis-tdd